/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uno;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import java.util.Collections;
import java.util.List;

public class Menu extends javax.swing.JFrame {
    private GameScreen gs;
    private GameControl controller;
    /**
     * Creates new form GUI
     */
    public Menu(){
        initComponents();
        this.controller = new GameControl();
        bgBlurred.setVisible(false);
    }
    public Menu(GameControl c){
        initComponents();
        this.controller = c;
        bgBlurred.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpScreen = new javax.swing.JInternalFrame();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)helpScreen.getUI()).setNorthPane(null);
        helpLabel = new javax.swing.JLabel();
        helpText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        bgLabel4 = new javax.swing.JLabel();
        gameSetup = new javax.swing.JInternalFrame();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)gameSetup.getUI()).setNorthPane(null);
        warningLabel = new javax.swing.JLabel();
        setupLabel = new javax.swing.JLabel();
        player4Label = new javax.swing.JLabel();
        diffCombo = new javax.swing.JComboBox<>();
        diffLabel = new javax.swing.JLabel();
        numplayerCombo = new javax.swing.JComboBox<>();
        playerLabel = new javax.swing.JLabel();
        player1Label = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        player3Label = new javax.swing.JLabel();
        player4Name = new javax.swing.JTextField();
        player1Name = new javax.swing.JTextField();
        player2Name = new javax.swing.JTextField();
        player3Name = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        bgLabel2 = new javax.swing.JLabel();
        bgBlurred = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        helpButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNO");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(68, 255, 73));
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(774, 547));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpScreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        helpScreen.setClosable(true);
        helpScreen.setTitle("Help");
        helpScreen.setToolTipText("");
        helpScreen.setVisible(false);
        helpScreen.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        helpLabel.setForeground(new java.awt.Color(255, 217, 0));
        helpLabel.setText("Help Text");
        helpLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        helpScreen.getContentPane().add(helpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 160, 40));

        helpText.setForeground(new java.awt.Color(255, 217, 0));
        helpText.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        helpText.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Uno is a card game played by at least two people.   \n\nThe objective of the game is to eliminate all of the cards in your hand.\nYou can play a single card on your turn, matching either the color, number, or action of the current card.  \n\nWild cards may be played when appropriate. \nCertain wild cards require the color to match (skip, reverse, draw two),while others can be played at any time (wild, wild draw four). \nThe second type allows the player to change the current playing color.\n\nWhen a card cannot be played, the player must draw. \nUpon reaching 1 card, the player must click \"UNO\" or else they will be forced to draw another card. ");
        jTextArea1.setToolTipText("");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea1.setMargin(new java.awt.Insets(100, 100, 2, 2));
        jTextArea1.setOpaque(false);
        helpText.setViewportView(jTextArea1);

        helpScreen.getContentPane().add(helpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 500, 310));

        bgLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bgLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgblurred.jpg"))); // NOI18N
        bgLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        helpScreen.getContentPane().add(bgLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 747, 540));

        getContentPane().add(helpScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 530, 400));

        gameSetup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        gameSetup.setClosable(true);
        gameSetup.setTitle("Game Setup");
        gameSetup.setToolTipText("");
        gameSetup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gameSetup.setVisible(false);
        gameSetup.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 255, 255));
        warningLabel.setText("Please make sure all fields are filled out.");
        warningLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        warningLabel.setFocusTraversalPolicyProvider(true);
        warningLabel.setVisible(false);
        gameSetup.getContentPane().add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        setupLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        setupLabel.setForeground(new java.awt.Color(255, 217, 0));
        setupLabel.setText("Game Setup");
        gameSetup.getContentPane().add(setupLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 160, 40));

        player4Label.setFont(player4Label.getFont().deriveFont(player4Label.getFont().getStyle() | java.awt.Font.BOLD));
        player4Label.setForeground(new java.awt.Color(255, 217, 0));
        player4Label.setText("Player 4:");
        player4Label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gameSetup.getContentPane().add(player4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 110, 30));

        diffCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Normal", "Hard", "ULTRA CHAOS MODE" }));
        diffCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        diffCombo.setFocusable(false);
        diffCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffComboActionPerformed(evt);
            }
        });
        gameSetup.getContentPane().add(diffCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        diffLabel.setFont(diffLabel.getFont().deriveFont(diffLabel.getFont().getStyle() | java.awt.Font.BOLD));
        diffLabel.setForeground(new java.awt.Color(255, 217, 0));
        diffLabel.setText("Difficulty:");
        diffLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gameSetup.getContentPane().add(diffLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 70, 30));

        numplayerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        numplayerCombo.setFocusable(false);
        numplayerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numplayerComboActionPerformed(evt);
            }
        });
        gameSetup.getContentPane().add(numplayerCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        playerLabel.setFont(playerLabel.getFont().deriveFont(playerLabel.getFont().getStyle() | java.awt.Font.BOLD));
        playerLabel.setForeground(new java.awt.Color(255, 217, 0));
        playerLabel.setText("Human Players:");
        playerLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gameSetup.getContentPane().add(playerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 110, 30));

        player1Label.setFont(player1Label.getFont().deriveFont(player1Label.getFont().getStyle() | java.awt.Font.BOLD));
        player1Label.setForeground(new java.awt.Color(255, 217, 0));
        player1Label.setText("Player 1:");
        player1Label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gameSetup.getContentPane().add(player1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 110, 30));

        player2Label.setFont(player2Label.getFont().deriveFont(player2Label.getFont().getStyle() | java.awt.Font.BOLD));
        player2Label.setForeground(new java.awt.Color(255, 217, 0));
        player2Label.setText("Player 2:");
        player2Label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gameSetup.getContentPane().add(player2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 110, 30));

        player3Label.setFont(player3Label.getFont().deriveFont(player3Label.getFont().getStyle() | java.awt.Font.BOLD));
        player3Label.setForeground(new java.awt.Color(255, 217, 0));
        player3Label.setText("Player 3:");
        player3Label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gameSetup.getContentPane().add(player3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 110, 30));

        player4Name.setText("Enter a name...");
        player4Name.setDisabledTextColor(new java.awt.Color(100, 100, 100));
        player4Name.setEnabled(false);
        player4Name.setText(getNames());
        gameSetup.getContentPane().add(player4Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 110, -1));

        player1Name.setToolTipText("");
        player1Name.setName(""); // NOI18N
        gameSetup.getContentPane().add(player1Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 110, -1));
        player1Name.getAccessibleContext().setAccessibleName("");

        player2Name.setText("Enter a name...");
        player2Name.setDisabledTextColor(new java.awt.Color(100, 100, 100));
        player2Name.setEnabled(false);
        player2Name.setText(getNames());
        player2Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2NameActionPerformed(evt);
            }
        });
        gameSetup.getContentPane().add(player2Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 110, -1));

        player3Name.setText("Enter a name...");
        player3Name.setDisabledTextColor(new java.awt.Color(100, 100, 100));
        player3Name.setEnabled(false);
        player3Name.setText(getNames());
        gameSetup.getContentPane().add(player3Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 110, -1));

        startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/start.png"))); // NOI18N
        startButton.setBorderPainted(false);
        startButton.setContentAreaFilled(false);
        startButton.setFocusable(false);
        startButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/startpush.png"))); // NOI18N
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        gameSetup.getContentPane().add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 200, 60));

        bgLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bgLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgblurred.jpg"))); // NOI18N
        bgLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gameSetup.getContentPane().add(bgLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -90, 747, 540));

        getContentPane().add(gameSetup, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 530, 400));

        bgBlurred.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/blurredbg.png"))); // NOI18N
        bgBlurred.setToolTipText("");
        bgBlurred.setBorder(null);
        bgBlurred.setBorderPainted(false);
        bgBlurred.setContentAreaFilled(false);
        bgBlurred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgBlurredActionPerformed(evt);
            }
        });
        getContentPane().add(bgBlurred, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        playButton.setBackground(new java.awt.Color(255, 255, 255));
        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/play.png"))); // NOI18N
        playButton.setBorderPainted(false);
        playButton.setContentAreaFilled(false);
        playButton.setFocusable(false);
        playButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/playpush.png"))); // NOI18N
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        logoLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        getContentPane().add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/help.png"))); // NOI18N
        helpButton.setBorderPainted(false);
        helpButton.setContentAreaFilled(false);
        helpButton.setFocusable(false);
        helpButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/helppush.png"))); // NOI18N
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(helpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        quitButton.setBackground(new java.awt.Color(255, 255, 255));
        quitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/quit.png"))); // NOI18N
        quitButton.setBorderPainted(false);
        quitButton.setContentAreaFilled(false);
        quitButton.setFocusable(false);
        quitButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/quitpush.png"))); // NOI18N
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(quitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        bgLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bg.jpg"))); // NOI18N
        bgLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        //Play
        bgBlurred.setVisible(true);
        gameSetup.setVisible(true);
    }//GEN-LAST:event_playButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        //Help
        bgBlurred.setVisible(true);
        helpScreen.setVisible(true);
    }//GEN-LAST:event_helpButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        //Quit
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void diffComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diffComboActionPerformed
    private String getNames(){
            String testName = this.controller.getNPCName();
            String[] arr = {player1Name.getText(),player2Name.getText(),player3Name.getText(),player4Name.getText()};
            for(int i=0;i<arr.length;i++){
                if(testName.equals(arr[i])){
                    i=0;
                    testName = this.controller.getNPCName();
                }
            }
            return testName;
        
    }
    private void numplayerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numplayerComboActionPerformed
        switch(Integer.parseInt(String.valueOf(numplayerCombo.getSelectedItem()))){
            case 1:
                player1Name.setEnabled(true);
                player2Name.setText(getNames());
                player3Name.setText(getNames());
                player4Name.setText(getNames());
                player2Name.setEnabled(false);
                player3Name.setEnabled(false);
                player4Name.setEnabled(false);
                break;
            case 2:
                player2Name.setEnabled(true);
                player2Name.setText("");
                player3Name.setText(getNames());
                player4Name.setText(getNames());
                player3Name.setEnabled(false);
                player4Name.setEnabled(false);
                break;
            case 3:
                player2Name.setEnabled(true);
                player3Name.setEnabled(true);
                player4Name.setEnabled(false);
                player2Name.setText("");
                player3Name.setText("");
                player4Name.setText(getNames());
                break;
            case 4:
                player2Name.setEnabled(true);
                player3Name.setEnabled(true);
                player4Name.setEnabled(true);
                player2Name.setText("");
                player3Name.setText("");
                player4Name.setText("");
                break;
        }
    }//GEN-LAST:event_numplayerComboActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        String[] pNames = {player1Name.getText(),player2Name.getText(),player3Name.getText(),player4Name.getText()};
        boolean[] NPC = {!player1Name.isEnabled(),!player2Name.isEnabled(),!player3Name.isEnabled(),!player4Name.isEnabled()};
        for(int i=0;i<Integer.parseInt(String.valueOf(numplayerCombo.getSelectedItem()));i++){
            if(pNames[i].replaceAll("\\s","").equals("")){
                warningLabel.setVisible(true);
                return;
            }
        }
        this.controller.setDifficulty(diffCombo.getSelectedIndex());
        this.controller.createPlayers(pNames,NPC);
        this.controller.initializeGamePlay();
        gs = new GameScreen(this.controller);
        gs.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_startButtonActionPerformed

    private void player2NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player2NameActionPerformed

    private void bgBlurredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgBlurredActionPerformed
        // TODO add your handling code here:
        bgBlurred.setVisible(false);
        helpScreen.setVisible(false);
        gameSetup.setVisible(false);
    }//GEN-LAST:event_bgBlurredActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bgBlurred;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel bgLabel2;
    private javax.swing.JLabel bgLabel4;
    private javax.swing.JComboBox<String> diffCombo;
    private javax.swing.JLabel diffLabel;
    private javax.swing.JInternalFrame gameSetup;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JInternalFrame helpScreen;
    private javax.swing.JScrollPane helpText;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JComboBox<String> numplayerCombo;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel player1Label;
    private javax.swing.JTextField player1Name;
    private javax.swing.JLabel player2Label;
    private javax.swing.JTextField player2Name;
    private javax.swing.JLabel player3Label;
    private javax.swing.JTextField player3Name;
    private javax.swing.JLabel player4Label;
    private javax.swing.JTextField player4Name;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel setupLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
